version: "3.7"

services:
  camel:
    container_name: api_web 
    build: 
      context: .
      dockerfile: ./.docker/CAMEL.Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE}
        - VCS_REF=${VCS_REF}
        - VERSION=${VERSION}
    ports:
      - "8888:80"
    restart: always
    command: gunicorn --bind 0.0.0.0:8888 manage:app
    volumes:
      - '.:/var/www/CAMEL'

  db:
    container_name: camel-database
    build:
      context: .
      dockerfile: ./.docker/DB.Dockerfile
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CAMEL
      MYSQL_USER: camel
      MYSQL_PASSWORD: abcdef
    ports:
      - "3306:3306"
